config/routes.rb
Rails.application.routes.draw do
  resources :care_providers
  resources :users
  resources :circles
  resources :patients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/care_provider.rb
class CareProvider < ApplicationRecord
  has_many :members
  has_many :circles, through: :members
end

app/controllers/care_providers_controller.rb
class CareProvidersController < ApplicationController
  before_action :set_care_provider, only: [:show, :edit, :update, :destroy]

  # GET /care_providers
  # GET /care_providers.json
  def index
    @care_providers = CareProvider.all
  end

  # GET /care_providers/1
  # GET /care_providers/1.json
  def show
  end

  # GET /care_providers/new
  def new
    @care_provider = CareProvider.new
  end

  # GET /care_providers/1/edit
  def edit
  end

  # POST /care_providers
  # POST /care_providers.json
  def create
    @care_provider = CareProvider.new(care_provider_params)

    respond_to do |format|
      if @care_provider.save
        format.html { redirect_to @care_provider, notice: 'Care provider was successfully created.' }
        format.json { render :show, status: :created, location: @care_provider }
      else
        format.html { render :new }
        format.json { render json: @care_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /care_providers/1
  # PATCH/PUT /care_providers/1.json
  def update
    respond_to do |format|
      if @care_provider.update(care_provider_params)
        format.html { redirect_to @care_provider, notice: 'Care provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @care_provider }
      else
        format.html { render :edit }
        format.json { render json: @care_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /care_providers/1
  # DELETE /care_providers/1.json
  def destroy
    @care_provider.destroy
    respond_to do |format|
      format.html { redirect_to care_providers_url, notice: 'Care provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_care_provider
      @care_provider = CareProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def care_provider_params
      params.require(:care_provider).permit(:name)
    end
end

app/helpers/care_providers_helper.rb
module CareProvidersHelper
end

app/views/care_providers/_form.html.erb
<%= form_with(model: care_provider, local: true) do |form| %>
  <% if care_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(care_provider.errors.count, "error") %> prohibited this care_provider from being saved:</h2>

      <ul>
        <% care_provider.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/care_providers/edit.html.erb
<h1>Editing Care Provider</h1>

<%= render 'form', care_provider: @care_provider %>

<%= link_to 'Show', @care_provider %> |
<%= link_to 'Back', care_providers_path %>

app/views/care_providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Care Providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @care_providers.each do |care_provider| %>
      <tr>
        <td><%= care_provider.name %></td>
        <td><%= link_to 'Show', care_provider %></td>
        <td><%= link_to 'Edit', edit_care_provider_path(care_provider) %></td>
        <td><%= link_to 'Destroy', care_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Care Provider', new_care_provider_path %>

app/views/care_providers/new.html.erb
<h1>New Care Provider</h1>

<%= render 'form', care_provider: @care_provider %>

<%= link_to 'Back', care_providers_path %>

app/views/care_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @care_provider.name %>
</p>

<%= link_to 'Edit', edit_care_provider_path(@care_provider) %> |
<%= link_to 'Back', care_providers_path %>