config/routes.rb
Rails.application.routes.draw do
  resources :care_providers
  resources :users
  resources :circles
  resources :patients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/circle.rb
class Circle < ApplicationRecord
  belongs_to :patient
  has_many :members
  has_many :care_providers, through: :members
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :set_circle, only: [:show, :edit, :update, :destroy]

  # GET /circles
  # GET /circles.json
  def index
    @circles = Circle.all
  end

  # GET /circles/1
  # GET /circles/1.json
  def show
  end

  # GET /circles/new
  def new
    @circle = Circle.new
  end

  # GET /circles/1/edit
  def edit
  end

  # POST /circles
  # POST /circles.json
  def create
    @circle = Circle.new(circle_params)

    respond_to do |format|
      if @circle.save
        format.html { redirect_to @circle, notice: 'Circle was successfully created.' }
        format.json { render :show, status: :created, location: @circle }
      else
        format.html { render :new }
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /circles/1
  # PATCH/PUT /circles/1.json
  def update
    respond_to do |format|
      if @circle.update(circle_params)
        format.html { redirect_to @circle, notice: 'Circle was successfully updated.' }
        format.json { render :show, status: :ok, location: @circle }
      else
        format.html { render :edit }
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /circles/1
  # DELETE /circles/1.json
  def destroy
    @circle.destroy
    respond_to do |format|
      format.html { redirect_to circles_url, notice: 'Circle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_circle
    @circle = Circle.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def circle_params
    params.require(:circle).permit(:subject, :name)
  end
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_form.html.erb
<%= form_with(model: circle, local: true) do |form| %>
  <% if circle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(circle.errors.count, "error") %> prohibited this circle from being saved:</h2>

      <ul>
        <% circle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/circles/edit.html.erb
<h1>Editing Circle</h1>

<%= render 'form', circle: @circle %>

<%= link_to 'Show', @circle %> |
<%= link_to 'Back', circles_path %>

app/views/circles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Circles</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Circle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @circles.each do |circle| %>
      <tr>
        <td><%= circle.patient.name %></td>
        <td><%= circle.name %></td>
        <td><%= link_to 'Show', circle %></td>
        <td><%= link_to 'Edit', edit_circle_path(circle) %></td>
        <td><%= link_to 'Destroy', circle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Circle', new_circle_path %>

app/views/circles/new.html.erb
<h1>New Circle</h1>

<%= render 'form', circle: @circle %>

<%= link_to 'Back', circles_path %>

app/views/circles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @circle.patient.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @circle.name %>
</p>

<%= link_to 'Edit', edit_circle_path(@circle) %> |
<%= link_to 'Back', circles_path %>